name: Preview pull request on Fly.io

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize, closed]

jobs:
 preview:
    runs-on: ubuntu-latest

    steps:
      - name: Say something
        run: echo "I love"
