name: Rebase web5Scripts onto main
on:
  push:
    branches:
      - main
jobs:
  rebase:
    name: Rebase `web5Scripts` onto `main`
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          ref: web5Scripts
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git rebase origin/main
          git push origin web5Scripts --force
